"""Canonical Hot 100 problem metadata shared by runtime services and builders.

This module is intentionally data-only.  It must not import scripts/build so
the production runtime can load the same catalog without importing build code.
"""
from __future__ import annotations

import re

PROBLEMS = [
  {
    "id": 1,
    "title": "两数之和",
    "category": "哈希表",
    "folder": "01-哈希表",
    "method": "一遍哈希",
    "time": "O(n)",
    "space": "O(n)",
    "invariant": "先查 target - x，再记录 x，避免元素与自身匹配",
    "difficulty": "简单"
  },
  {
    "id": 49,
    "title": "字母异位词分组",
    "category": "哈希表",
    "folder": "01-哈希表",
    "method": "排序签名 + 哈希分组",
    "time": "O(n·k log k)",
    "space": "O(n·k)",
    "invariant": "异位词必须映射成同一个稳定签名",
    "difficulty": "中等"
  },
  {
    "id": 128,
    "title": "最长连续序列",
    "category": "哈希表",
    "folder": "01-哈希表",
    "method": "哈希集合找序列起点",
    "time": "O(n)",
    "space": "O(n)",
    "invariant": "只从不存在 x - 1 的数字开始向右扩展",
    "difficulty": "中等"
  },
  {
    "id": 283,
    "title": "移动零",
    "category": "双指针",
    "folder": "02-双指针",
    "method": "快慢指针原地交换",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "slow 始终指向下一个非零元素应放的位置",
    "difficulty": "简单"
  },
  {
    "id": 11,
    "title": "盛最多水的容器",
    "category": "双指针",
    "folder": "02-双指针",
    "method": "相向双指针",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "移动短板才可能抵消宽度缩小带来的损失",
    "difficulty": "中等"
  },
  {
    "id": 15,
    "title": "三数之和",
    "category": "双指针",
    "folder": "02-双指针",
    "method": "排序 + 固定一点 + 双指针",
    "time": "O(n²)",
    "space": "O(log n)",
    "invariant": "固定第一数后夹逼，并在三层位置正确去重",
    "difficulty": "中等"
  },
  {
    "id": 42,
    "title": "接雨水",
    "category": "双指针",
    "folder": "02-双指针",
    "method": "左右最大值双指针",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "较低一侧的蓄水量已由该侧最大边界确定",
    "difficulty": "困难"
  },
  {
    "id": 3,
    "title": "无重复字符的最长子串",
    "category": "滑动窗口",
    "folder": "03-滑动窗口",
    "method": "可变滑动窗口",
    "time": "O(n)",
    "space": "O(字符集)",
    "invariant": "窗口内始终无重复，left 只能向右不能回退",
    "difficulty": "中等"
  },
  {
    "id": 438,
    "title": "找到字符串中所有字母异位词",
    "category": "滑动窗口",
    "folder": "03-滑动窗口",
    "method": "定长窗口 + 频次表",
    "time": "O(n)",
    "space": "O(字符集)",
    "invariant": "窗口长度固定，频次完全匹配时记录左端点",
    "difficulty": "中等"
  },
  {
    "id": 560,
    "title": "和为 K 的子数组",
    "category": "子串",
    "folder": "04-子串",
    "method": "前缀和 + 频次哈希",
    "time": "O(n)",
    "space": "O(n)",
    "invariant": "当前前缀为 pre 时，需要此前出现过 pre - k",
    "difficulty": "中等"
  },
  {
    "id": 239,
    "title": "滑动窗口最大值",
    "category": "子串",
    "folder": "04-子串",
    "method": "单调队列",
    "time": "O(n)",
    "space": "O(k)",
    "invariant": "队列保存有效下标，且对应值从队首到队尾递减",
    "difficulty": "困难"
  },
  {
    "id": 76,
    "title": "最小覆盖子串",
    "category": "子串",
    "folder": "04-子串",
    "method": "可变滑动窗口 + 计数",
    "time": "O(m+n)",
    "space": "O(字符集)",
    "invariant": "右扩直到满足，左缩直到刚好不满足",
    "difficulty": "困难"
  },
  {
    "id": 53,
    "title": "最大子数组和",
    "category": "普通数组",
    "folder": "05-普通数组",
    "method": "Kadane 动态规划",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "前一段和为负时不值得被当前位置继承",
    "difficulty": "中等"
  },
  {
    "id": 56,
    "title": "合并区间",
    "category": "普通数组",
    "folder": "05-普通数组",
    "method": "排序 + 线性合并",
    "time": "O(n log n)",
    "space": "O(log n)",
    "invariant": "每个新区间只需和结果中的最后一个区间比较",
    "difficulty": "中等"
  },
  {
    "id": 189,
    "title": "轮转数组",
    "category": "普通数组",
    "folder": "05-普通数组",
    "method": "三次反转",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "整体反转后再分别恢复前 k 段和后 n-k 段的顺序",
    "difficulty": "中等"
  },
  {
    "id": 238,
    "title": "除自身以外数组的乘积",
    "category": "普通数组",
    "folder": "05-普通数组",
    "method": "前缀积 + 后缀积",
    "time": "O(n)",
    "space": "O(1) 除答案外",
    "invariant": "答案先保存左侧乘积，再乘滚动的右侧乘积",
    "difficulty": "中等"
  },
  {
    "id": 41,
    "title": "缺失的第一个正数",
    "category": "普通数组",
    "folder": "05-普通数组",
    "method": "原地哈希 / 循环置换",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "值 x 的理想位置是下标 x - 1",
    "difficulty": "困难"
  },
  {
    "id": 73,
    "title": "矩阵置零",
    "category": "矩阵",
    "folder": "06-矩阵",
    "method": "首行首列原地标记",
    "time": "O(mn)",
    "space": "O(1)",
    "invariant": "首行首列兼作标记，另存它们自身是否需要清零",
    "difficulty": "中等"
  },
  {
    "id": 54,
    "title": "螺旋矩阵",
    "category": "矩阵",
    "folder": "06-矩阵",
    "method": "四边界模拟",
    "time": "O(mn)",
    "space": "O(1)",
    "invariant": "走完一条边立刻收缩对应边界，并防止重复访问",
    "difficulty": "中等"
  },
  {
    "id": 48,
    "title": "旋转图像",
    "category": "矩阵",
    "folder": "06-矩阵",
    "method": "转置 + 每行反转",
    "time": "O(n²)",
    "space": "O(1)",
    "invariant": "转置完成行列交换，水平翻转完成顺时针旋转",
    "difficulty": "中等"
  },
  {
    "id": 240,
    "title": "搜索二维矩阵 II",
    "category": "矩阵",
    "folder": "06-矩阵",
    "method": "右上角阶梯搜索",
    "time": "O(m+n)",
    "space": "O(1)",
    "invariant": "每次比较都能排除一整行或一整列",
    "difficulty": "中等"
  },
  {
    "id": 160,
    "title": "相交链表",
    "category": "链表",
    "folder": "07-链表",
    "method": "双指针换头",
    "time": "O(m+n)",
    "space": "O(1)",
    "invariant": "两指针各走 A+B 后自然对齐，比较的是节点引用",
    "difficulty": "简单"
  },
  {
    "id": 234,
    "title": "回文链表",
    "category": "链表",
    "folder": "07-链表",
    "method": "找中点 + 反转后半段",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "只比较等长的两半，结束后恢复链表更稳妥",
    "difficulty": "简单"
  },
  {
    "id": 206,
    "title": "反转链表",
    "category": "链表",
    "folder": "07-链表",
    "method": "迭代三指针",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "修改 next 前必须先保存原来的后继",
    "difficulty": "简单"
  },
  {
    "id": 141,
    "title": "环形链表",
    "category": "链表",
    "folder": "07-链表",
    "method": "Floyd 快慢指针",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "有环时快指针一定会在环内追上慢指针",
    "difficulty": "简单"
  },
  {
    "id": 142,
    "title": "环形链表 II",
    "category": "链表",
    "folder": "07-链表",
    "method": "Floyd 相遇后重置",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "相遇后一个回到头部，同速再走会在入口相遇",
    "difficulty": "中等"
  },
  {
    "id": 21,
    "title": "合并两个有序链表",
    "category": "链表",
    "folder": "07-链表",
    "method": "虚拟头节点 + 尾插",
    "time": "O(m+n)",
    "space": "O(1)",
    "invariant": "tail 始终指向已合并部分的最后一个节点",
    "difficulty": "简单"
  },
  {
    "id": 2,
    "title": "两数相加",
    "category": "链表",
    "folder": "07-链表",
    "method": "逐位模拟 + 进位",
    "time": "O(max(m,n))",
    "space": "O(1) 除答案外",
    "invariant": "循环条件必须包含两个链表和最后的 carry",
    "difficulty": "中等"
  },
  {
    "id": 19,
    "title": "删除链表的倒数第 N 个结点",
    "category": "链表",
    "folder": "07-链表",
    "method": "快慢指针 + 虚拟头",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "fast 先走 n 步，随后保持固定间距",
    "difficulty": "中等"
  },
  {
    "id": 24,
    "title": "两两交换链表中的节点",
    "category": "链表",
    "folder": "07-链表",
    "method": "虚拟头 + 局部重连",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "每轮保存下一组入口，再按固定顺序改三条指针",
    "difficulty": "中等"
  },
  {
    "id": 25,
    "title": "K 个一组翻转链表",
    "category": "链表",
    "folder": "07-链表",
    "method": "分组检测 + 区间反转",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "不足 k 个保持原样；先确定组尾再反转",
    "difficulty": "困难"
  },
  {
    "id": 138,
    "title": "随机链表的复制",
    "category": "链表",
    "folder": "07-链表",
    "method": "节点穿插复制",
    "time": "O(n)",
    "space": "O(1) 除答案外",
    "invariant": "复制节点紧跟原节点，random 可由 original.random.next 得到",
    "difficulty": "中等"
  },
  {
    "id": 148,
    "title": "排序链表",
    "category": "链表",
    "folder": "07-链表",
    "method": "归并排序",
    "time": "O(n log n)",
    "space": "O(1) 可用自底向上",
    "invariant": "链表适合通过断链、归并完成稳定排序",
    "difficulty": "中等"
  },
  {
    "id": 23,
    "title": "合并 K 个升序链表",
    "category": "链表",
    "folder": "07-链表",
    "method": "最小堆多路归并",
    "time": "O(N log k)",
    "space": "O(k)",
    "invariant": "堆中始终只放每条链表当前最小的头节点",
    "difficulty": "困难"
  },
  {
    "id": 146,
    "title": "LRU 缓存",
    "category": "链表",
    "folder": "07-链表",
    "method": "哈希表 + 双向链表",
    "time": "O(1)",
    "space": "O(capacity)",
    "invariant": "哈希负责定位，双链表负责 O(1) 调整新旧顺序",
    "difficulty": "中等"
  },
  {
    "id": 94,
    "title": "二叉树的中序遍历",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "递归 / 栈 / Morris",
    "time": "O(n)",
    "space": "O(h)，Morris 为 O(1)",
    "invariant": "中序顺序是左—根—右，BST 中对应升序",
    "difficulty": "简单"
  },
  {
    "id": 104,
    "title": "二叉树的最大深度",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "后序 DFS",
    "time": "O(n)",
    "space": "O(h)",
    "invariant": "节点深度等于左右子树最大深度加一",
    "difficulty": "简单"
  },
  {
    "id": 226,
    "title": "翻转二叉树",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "递归交换左右子树",
    "time": "O(n)",
    "space": "O(h)",
    "invariant": "每个节点只做一件事：交换左右孩子",
    "difficulty": "简单"
  },
  {
    "id": 101,
    "title": "对称二叉树",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "镜像递归 / 队列",
    "time": "O(n)",
    "space": "O(h)",
    "invariant": "成对比较外侧与外侧、内侧与内侧",
    "difficulty": "简单"
  },
  {
    "id": 543,
    "title": "二叉树的直径",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "后序高度 + 全局答案",
    "time": "O(n)",
    "space": "O(h)",
    "invariant": "经过当前节点的直径是左高加右高",
    "difficulty": "中等"
  },
  {
    "id": 102,
    "title": "二叉树的层序遍历",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "BFS 分层",
    "time": "O(n)",
    "space": "O(w)",
    "invariant": "每轮先固定队列长度，它就是当前层节点数",
    "difficulty": "中等"
  },
  {
    "id": 108,
    "title": "将有序数组转换为二叉搜索树",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "分治取中点",
    "time": "O(n)",
    "space": "O(log n)",
    "invariant": "中点作根可同时保证 BST 有序与高度平衡",
    "difficulty": "简单"
  },
  {
    "id": 98,
    "title": "验证二叉搜索树",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "上下界递归 / 中序",
    "time": "O(n)",
    "space": "O(h)",
    "invariant": "约束作用于整棵子树，不只是父子节点",
    "difficulty": "中等"
  },
  {
    "id": 230,
    "title": "二叉搜索树中第 K 小的元素",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "中序遍历提前停止",
    "time": "O(h+k)",
    "space": "O(h)",
    "invariant": "BST 中序序列严格递增",
    "difficulty": "中等"
  },
  {
    "id": 199,
    "title": "二叉树的右视图",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "分层 BFS / 右优先 DFS",
    "time": "O(n)",
    "space": "O(h)",
    "invariant": "每一层只记录最后访问或最先访问的右侧节点",
    "difficulty": "中等"
  },
  {
    "id": 114,
    "title": "二叉树展开为链表",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "逆前序递归",
    "time": "O(n)",
    "space": "O(h)",
    "invariant": "按右—左—根处理，prev 始终是当前节点应接的后继",
    "difficulty": "中等"
  },
  {
    "id": 105,
    "title": "从前序与中序遍历序列构造二叉树",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "前序指针 + 中序索引表",
    "time": "O(n)",
    "space": "O(n)",
    "invariant": "前序决定根，中序决定左右子树边界",
    "difficulty": "中等"
  },
  {
    "id": 437,
    "title": "路径总和 III",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "前缀和 DFS",
    "time": "O(n)",
    "space": "O(h)",
    "invariant": "当前前缀为 sum 时，祖先前缀 sum-target 的次数就是新增路径数",
    "difficulty": "中等"
  },
  {
    "id": 236,
    "title": "二叉树的最近公共祖先",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "后序递归",
    "time": "O(n)",
    "space": "O(h)",
    "invariant": "左右子树各找到一个目标时，当前节点就是最近公共祖先",
    "difficulty": "中等"
  },
  {
    "id": 124,
    "title": "二叉树中的最大路径和",
    "category": "二叉树",
    "folder": "08-二叉树",
    "method": "后序最大贡献",
    "time": "O(n)",
    "space": "O(h)",
    "invariant": "向上只能贡献一条支路，更新答案时可以同时取左右支路",
    "difficulty": "困难"
  },
  {
    "id": 200,
    "title": "岛屿数量",
    "category": "图论",
    "folder": "09-图论",
    "method": "DFS / BFS 洪泛",
    "time": "O(mn)",
    "space": "O(mn)",
    "invariant": "发现陆地就立刻标记并扩展整座岛",
    "difficulty": "中等"
  },
  {
    "id": 994,
    "title": "腐烂的橘子",
    "category": "图论",
    "folder": "09-图论",
    "method": "多源 BFS",
    "time": "O(mn)",
    "space": "O(mn)",
    "invariant": "所有初始腐烂橘子同时作为第 0 分钟入队",
    "difficulty": "中等"
  },
  {
    "id": 207,
    "title": "课程表",
    "category": "图论",
    "folder": "09-图论",
    "method": "Kahn 拓扑排序",
    "time": "O(V+E)",
    "space": "O(V+E)",
    "invariant": "每学完一门课就减少后继入度，最终处理数应等于课程数",
    "difficulty": "中等"
  },
  {
    "id": 208,
    "title": "实现 Trie",
    "category": "图论",
    "folder": "09-图论",
    "method": "前缀树",
    "time": "O(总字符数)",
    "space": "O(总字符数)",
    "invariant": "路径表示前缀，结束标记区分完整单词与前缀",
    "difficulty": "中等"
  },
  {
    "id": 46,
    "title": "全排列",
    "category": "回溯",
    "folder": "10-回溯",
    "method": "路径 + used 数组",
    "time": "O(n·n!)",
    "space": "O(n)",
    "invariant": "同一条路径中每个元素只能使用一次",
    "difficulty": "中等"
  },
  {
    "id": 78,
    "title": "子集",
    "category": "回溯",
    "folder": "10-回溯",
    "method": "起点索引回溯",
    "time": "O(n·2ⁿ)",
    "space": "O(n)",
    "invariant": "每个递归节点本身就是一个合法子集",
    "difficulty": "中等"
  },
  {
    "id": 17,
    "title": "电话号码的字母组合",
    "category": "回溯",
    "folder": "10-回溯",
    "method": "按位选择字符",
    "time": "O(4ⁿ)",
    "space": "O(n)",
    "invariant": "递归层数对应电话号码下标",
    "difficulty": "中等"
  },
  {
    "id": 39,
    "title": "组合总和",
    "category": "回溯",
    "folder": "10-回溯",
    "method": "排序 + 可重复选择",
    "time": "指数级",
    "space": "O(target)",
    "invariant": "允许复用当前数，因此下一层仍从 i 开始",
    "difficulty": "中等"
  },
  {
    "id": 22,
    "title": "括号生成",
    "category": "回溯",
    "folder": "10-回溯",
    "method": "计数约束剪枝",
    "time": "O(Cₙ)",
    "space": "O(n)",
    "invariant": "任意前缀中右括号数不能超过左括号数",
    "difficulty": "中等"
  },
  {
    "id": 79,
    "title": "单词搜索",
    "category": "回溯",
    "folder": "10-回溯",
    "method": "网格 DFS + 原地标记",
    "time": "O(mn·4ᴸ)",
    "space": "O(L)",
    "invariant": "一个格子在同一路径中只能使用一次，返回前恢复",
    "difficulty": "中等"
  },
  {
    "id": 131,
    "title": "分割回文串",
    "category": "回溯",
    "folder": "10-回溯",
    "method": "切割回溯 + 回文判断",
    "time": "O(n·2ⁿ)",
    "space": "O(n²)",
    "invariant": "只有当前切片是回文串时才进入下一层",
    "difficulty": "中等"
  },
  {
    "id": 51,
    "title": "N 皇后",
    "category": "回溯",
    "folder": "10-回溯",
    "method": "列与两条对角线约束",
    "time": "O(n!)",
    "space": "O(n)",
    "invariant": "row-col 与 row+col 分别唯一标识两类对角线",
    "difficulty": "困难"
  },
  {
    "id": 35,
    "title": "搜索插入位置",
    "category": "二分查找",
    "folder": "11-二分查找",
    "method": "lower_bound",
    "time": "O(log n)",
    "space": "O(1)",
    "invariant": "寻找第一个大于等于 target 的下标",
    "difficulty": "简单"
  },
  {
    "id": 74,
    "title": "搜索二维矩阵",
    "category": "二分查找",
    "folder": "11-二分查找",
    "method": "二维下标映射一维",
    "time": "O(log(mn))",
    "space": "O(1)",
    "invariant": "mid / n 得行，mid % n 得列",
    "difficulty": "中等"
  },
  {
    "id": 33,
    "title": "搜索旋转排序数组",
    "category": "二分查找",
    "folder": "11-二分查找",
    "method": "识别有序半边",
    "time": "O(log n)",
    "space": "O(1)",
    "invariant": "每轮至少有一半有序，再判断 target 是否落在其中",
    "difficulty": "中等"
  },
  {
    "id": 153,
    "title": "寻找旋转排序数组中的最小值",
    "category": "二分查找",
    "folder": "11-二分查找",
    "method": "mid 与 right 比较",
    "time": "O(log n)",
    "space": "O(1)",
    "invariant": "nums[mid] > nums[right] 时最小值一定在右侧",
    "difficulty": "中等"
  },
  {
    "id": 4,
    "title": "寻找两个正序数组的中位数",
    "category": "二分查找",
    "folder": "11-二分查找",
    "method": "短数组上二分分割线",
    "time": "O(log min(m,n))",
    "space": "O(1)",
    "invariant": "正确分割满足左半最大值不大于右半最小值",
    "difficulty": "困难"
  },
  {
    "id": 20,
    "title": "有效的括号",
    "category": "栈",
    "folder": "12-栈",
    "method": "栈保存期待的右括号",
    "time": "O(n)",
    "space": "O(n)",
    "invariant": "遇到右括号时必须与栈顶期待值一致",
    "difficulty": "简单"
  },
  {
    "id": 155,
    "title": "最小栈",
    "category": "栈",
    "folder": "12-栈",
    "method": "数据栈 + 最小值栈",
    "time": "O(1)",
    "space": "O(n)",
    "invariant": "辅助栈顶始终是当前所有元素的最小值",
    "difficulty": "中等"
  },
  {
    "id": 394,
    "title": "字符串解码",
    "category": "栈",
    "folder": "12-栈",
    "method": "保存外层次数与字符串",
    "time": "O(n)",
    "space": "O(n)",
    "invariant": "遇到 [ 保存现场，遇到 ] 恢复上一层并展开当前层",
    "difficulty": "中等"
  },
  {
    "id": 739,
    "title": "每日温度",
    "category": "栈",
    "folder": "12-栈",
    "method": "单调递减索引栈",
    "time": "O(n)",
    "space": "O(n)",
    "invariant": "栈内下标对应温度递减，升温时批量结算",
    "difficulty": "中等"
  },
  {
    "id": 84,
    "title": "柱状图中最大的矩形",
    "category": "栈",
    "folder": "12-栈",
    "method": "单调递增栈 + 哨兵",
    "time": "O(n)",
    "space": "O(n)",
    "invariant": "出栈时当前柱子的左右第一个更矮边界已经确定",
    "difficulty": "困难"
  },
  {
    "id": 232,
    "title": "用栈实现队列",
    "category": "栈",
    "folder": "12-栈",
    "method": "输入栈 + 输出栈",
    "time": "均摊 O(1)",
    "space": "O(n)",
    "invariant": "输出栈为空时才把输入栈全部倒入",
    "difficulty": "简单"
  },
  {
    "id": 215,
    "title": "数组中的第K个最大元素",
    "category": "堆",
    "folder": "13-堆",
    "method": "大小为 k 的小顶堆 / 快选",
    "time": "O(n log k)",
    "space": "O(k)",
    "invariant": "堆顶始终是当前前 k 大中的最小者",
    "difficulty": "中等"
  },
  {
    "id": 347,
    "title": "前 K 个高频元素",
    "category": "堆",
    "folder": "13-堆",
    "method": "频次表 + 小顶堆",
    "time": "O(n log k)",
    "space": "O(n)",
    "invariant": "堆按频次比较，只保留频次最高的 k 个键",
    "difficulty": "中等"
  },
  {
    "id": 295,
    "title": "数据流的中位数",
    "category": "堆",
    "folder": "13-堆",
    "method": "大顶堆 + 小顶堆",
    "time": "插入 O(log n)，查询 O(1)",
    "space": "O(n)",
    "invariant": "两堆元素数之差不超过一，且左堆所有值不大于右堆",
    "difficulty": "困难"
  },
  {
    "id": 121,
    "title": "买卖股票的最佳时机",
    "category": "贪心",
    "folder": "14-贪心",
    "method": "维护历史最低价",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "卖出当天只需要此前最低买入价",
    "difficulty": "简单"
  },
  {
    "id": 55,
    "title": "跳跃游戏",
    "category": "贪心",
    "folder": "14-贪心",
    "method": "维护最远可达位置",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "遍历位置必须不超过 farthest",
    "difficulty": "中等"
  },
  {
    "id": 45,
    "title": "跳跃游戏 II",
    "category": "贪心",
    "folder": "14-贪心",
    "method": "分层最远边界",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "到达当前层边界时才增加一步并更新下一层边界",
    "difficulty": "中等"
  },
  {
    "id": 763,
    "title": "划分字母区间",
    "category": "贪心",
    "folder": "14-贪心",
    "method": "最后出现位置",
    "time": "O(n)",
    "space": "O(字符集)",
    "invariant": "当前片段结束位置是片段内所有字符最后位置的最大值",
    "difficulty": "中等"
  },
  {
    "id": 70,
    "title": "爬楼梯",
    "category": "动态规划",
    "folder": "15-动态规划",
    "method": "滚动 Fibonacci",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "到第 i 阶只能来自 i-1 或 i-2",
    "difficulty": "简单"
  },
  {
    "id": 118,
    "title": "杨辉三角",
    "category": "动态规划",
    "folder": "15-动态规划",
    "method": "逐行递推",
    "time": "O(n²)",
    "space": "O(n²)",
    "invariant": "内部元素来自上一行左上与正上方",
    "difficulty": "简单"
  },
  {
    "id": 198,
    "title": "打家劫舍",
    "category": "动态规划",
    "folder": "15-动态规划",
    "method": "选或不选滚动状态",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "dp[i] 只比较跳过当前与偷当前两种选择",
    "difficulty": "中等"
  },
  {
    "id": 279,
    "title": "完全平方数",
    "category": "动态规划",
    "folder": "15-动态规划",
    "method": "完全背包",
    "time": "O(n√n)",
    "space": "O(n)",
    "invariant": "dp[i] 从所有不超过 i 的平方数转移",
    "difficulty": "中等"
  },
  {
    "id": 322,
    "title": "零钱兑换",
    "category": "动态规划",
    "folder": "15-动态规划",
    "method": "完全背包最小值",
    "time": "O(amount·coins)",
    "space": "O(amount)",
    "invariant": "正序遍历容量允许同一枚硬币重复使用",
    "difficulty": "中等"
  },
  {
    "id": 139,
    "title": "单词拆分",
    "category": "动态规划",
    "folder": "15-动态规划",
    "method": "前缀可达性",
    "time": "O(n²)",
    "space": "O(n)",
    "invariant": "dp[i] 表示前 i 个字符是否可由字典组成",
    "difficulty": "中等"
  },
  {
    "id": 300,
    "title": "最长递增子序列",
    "category": "动态规划",
    "folder": "15-动态规划",
    "method": "DP / 贪心二分",
    "time": "O(n log n)",
    "space": "O(n)",
    "invariant": "tails[len] 保存该长度递增子序列最小可能结尾",
    "difficulty": "中等"
  },
  {
    "id": 152,
    "title": "乘积最大子数组",
    "category": "动态规划",
    "folder": "15-动态规划",
    "method": "同时维护最大积与最小积",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "负数会交换最大与最小角色",
    "difficulty": "中等"
  },
  {
    "id": 416,
    "title": "分割等和子集",
    "category": "动态规划",
    "folder": "15-动态规划",
    "method": "0-1 背包",
    "time": "O(n·target)",
    "space": "O(target)",
    "invariant": "容量倒序保证每个数字只使用一次",
    "difficulty": "中等"
  },
  {
    "id": 32,
    "title": "最长有效括号",
    "category": "动态规划",
    "folder": "15-动态规划",
    "method": "以右括号结尾的 DP",
    "time": "O(n)",
    "space": "O(n)",
    "invariant": "dp[i] 只表示必须以 i 结尾的最长有效长度",
    "difficulty": "困难"
  },
  {
    "id": 62,
    "title": "不同路径",
    "category": "多维动态规划",
    "folder": "16-多维动态规划",
    "method": "网格路径计数",
    "time": "O(mn)",
    "space": "O(n)",
    "invariant": "当前位置方案数来自上方与左方",
    "difficulty": "中等"
  },
  {
    "id": 64,
    "title": "最小路径和",
    "category": "多维动态规划",
    "folder": "16-多维动态规划",
    "method": "网格最小代价",
    "time": "O(mn)",
    "space": "O(1) 可原地",
    "invariant": "当前位置最小代价来自上方和左方较小者",
    "difficulty": "中等"
  },
  {
    "id": 5,
    "title": "最长回文子串",
    "category": "多维动态规划",
    "folder": "16-多维动态规划",
    "method": "区间 DP / 中心扩展",
    "time": "O(n²)",
    "space": "O(n²)，中心扩展 O(1)",
    "invariant": "两端字符相同且内部是回文，当前区间才是回文",
    "difficulty": "中等"
  },
  {
    "id": 1143,
    "title": "最长公共子序列",
    "category": "多维动态规划",
    "folder": "16-多维动态规划",
    "method": "双序列 DP",
    "time": "O(mn)",
    "space": "O(mn)",
    "invariant": "字符相同取左上加一，否则取上方与左方最大值",
    "difficulty": "中等"
  },
  {
    "id": 72,
    "title": "编辑距离",
    "category": "多维动态规划",
    "folder": "16-多维动态规划",
    "method": "双序列 DP",
    "time": "O(mn)",
    "space": "O(mn)",
    "invariant": "最后字符相同不付代价，否则从增删改三种操作取最小",
    "difficulty": "困难"
  },
  {
    "id": 136,
    "title": "只出现一次的数字",
    "category": "技巧",
    "folder": "17-技巧",
    "method": "异或消去",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "x xor x = 0，且 0 xor x = x",
    "difficulty": "简单"
  },
  {
    "id": 169,
    "title": "多数元素",
    "category": "技巧",
    "folder": "17-技巧",
    "method": "Boyer-Moore 投票",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "不同元素两两抵消后，多数元素仍会剩下",
    "difficulty": "简单"
  },
  {
    "id": 75,
    "title": "颜色分类",
    "category": "技巧",
    "folder": "17-技巧",
    "method": "荷兰国旗三指针",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "[0,left) 是 0，[left,i) 是 1，(right,n) 是 2",
    "difficulty": "中等"
  },
  {
    "id": 31,
    "title": "下一个排列",
    "category": "技巧",
    "folder": "17-技巧",
    "method": "找拐点、交换、反转后缀",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "从右侧找到仍可增大的最靠右位置，并使用最小增量",
    "difficulty": "中等"
  },
  {
    "id": 287,
    "title": "寻找重复数",
    "category": "技巧",
    "folder": "17-技巧",
    "method": "Floyd 隐式链表",
    "time": "O(n)",
    "space": "O(1)",
    "invariant": "把下标到数值看作 next 指针，重复值就是环入口",
    "difficulty": "中等"
  }
]
PROBLEM_BY_ID = {int(problem["id"]): problem for problem in PROBLEMS}

LEETCODE_BASE = "https://leetcode.cn/problems/{slug}/?envType=study-plan-v2&envId=top-100-liked"
_LEETCODE_SLUGS = {
  "1": "two-sum",
  "2": "add-two-numbers",
  "3": "longest-substring-without-repeating-characters",
  "4": "median-of-two-sorted-arrays",
  "5": "longest-palindromic-substring",
  "11": "container-with-most-water",
  "15": "3sum",
  "17": "letter-combinations-of-a-phone-number",
  "19": "remove-nth-node-from-end-of-list",
  "20": "valid-parentheses",
  "21": "merge-two-sorted-lists",
  "22": "generate-parentheses",
  "23": "merge-k-sorted-lists",
  "24": "swap-nodes-in-pairs",
  "25": "reverse-nodes-in-k-group",
  "31": "next-permutation",
  "32": "longest-valid-parentheses",
  "33": "search-in-rotated-sorted-array",
  "35": "search-insert-position",
  "39": "combination-sum",
  "41": "first-missing-positive",
  "42": "trapping-rain-water",
  "45": "jump-game-ii",
  "46": "permutations",
  "48": "rotate-image",
  "49": "group-anagrams",
  "51": "n-queens",
  "53": "maximum-subarray",
  "54": "spiral-matrix",
  "55": "jump-game",
  "56": "merge-intervals",
  "62": "unique-paths",
  "64": "minimum-path-sum",
  "70": "climbing-stairs",
  "72": "edit-distance",
  "73": "set-matrix-zeroes",
  "74": "search-a-2d-matrix",
  "75": "sort-colors",
  "76": "minimum-window-substring",
  "78": "subsets",
  "79": "word-search",
  "84": "largest-rectangle-in-histogram",
  "94": "binary-tree-inorder-traversal",
  "98": "validate-binary-search-tree",
  "101": "symmetric-tree",
  "102": "binary-tree-level-order-traversal",
  "104": "maximum-depth-of-binary-tree",
  "105": "construct-binary-tree-from-preorder-and-inorder-traversal",
  "108": "convert-sorted-array-to-binary-search-tree",
  "114": "flatten-binary-tree-to-linked-list",
  "118": "pascals-triangle",
  "121": "best-time-to-buy-and-sell-stock",
  "124": "binary-tree-maximum-path-sum",
  "128": "longest-consecutive-sequence",
  "131": "palindrome-partitioning",
  "136": "single-number",
  "138": "copy-list-with-random-pointer",
  "139": "word-break",
  "141": "linked-list-cycle",
  "142": "linked-list-cycle-ii",
  "146": "lru-cache",
  "148": "sort-list",
  "152": "maximum-product-subarray",
  "153": "find-minimum-in-rotated-sorted-array",
  "155": "min-stack",
  "160": "intersection-of-two-linked-lists",
  "169": "majority-element",
  "189": "rotate-array",
  "198": "house-robber",
  "199": "binary-tree-right-side-view",
  "200": "number-of-islands",
  "206": "reverse-linked-list",
  "207": "course-schedule",
  "208": "implement-trie-prefix-tree",
  "215": "kth-largest-element-in-an-array",
  "226": "invert-binary-tree",
  "230": "kth-smallest-element-in-a-bst",
  "232": "implement-queue-using-stacks",
  "234": "palindrome-linked-list",
  "236": "lowest-common-ancestor-of-a-binary-tree",
  "238": "product-of-array-except-self",
  "239": "sliding-window-maximum",
  "240": "search-a-2d-matrix-ii",
  "279": "perfect-squares",
  "283": "move-zeroes",
  "287": "find-the-duplicate-number",
  "295": "find-median-from-data-stream",
  "300": "longest-increasing-subsequence",
  "322": "coin-change",
  "347": "top-k-frequent-elements",
  "394": "decode-string",
  "416": "partition-equal-subset-sum",
  "437": "path-sum-iii",
  "438": "find-all-anagrams-in-a-string",
  "543": "diameter-of-binary-tree",
  "560": "subarray-sum-equals-k",
  "739": "daily-temperatures",
  "763": "partition-labels",
  "994": "rotting-oranges",
  "1143": "longest-common-subsequence"
}
LEETCODE_SLUGS = {int(problem_id): slug for problem_id, slug in _LEETCODE_SLUGS.items()}

def _safe_name(text: str) -> str:
    return re.sub(r'[<>:"/\\|?*]', "-", text).strip().rstrip(".")

def problem_filename(problem: dict[str, object]) -> str:
    return f"{int(problem['id']):04d}-{_safe_name(str(problem['title']))}.md"

